ProiectV1/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProiectV1.Data;
using ProiectV1.Models;

namespace ProiectV1.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<Profile> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public CategoriesController(ApplicationDbContext context,
                                    UserManager<Profile> userManager,
                                    RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var categories = from category in db.Categories
                             orderby category.CategoryName
                             select category;
            ViewBag.Categories = categories;

            ViewBag.IsAdmin = User.IsInRole("Admin");


            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
            return View();
        }

        
        public ActionResult Show(int id)
        {
            Category category = db.Categories.Find(id);
            if(category == null)
            {
                TempData["message"] = "Categoria nu exista";
                return RedirectToAction("Index");
            }
            ViewBag.IsAdmin = User.IsInRole("Admin");
            category = db.Categories.Include("Products").Where(categ => categ.Id == id).First();
            return View(category);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult New()
        {   
            
              return View();

        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult New(Category cat)
        {
           
                try
                {
                    db.Categories.Add(cat);
                    db.SaveChanges();
                    TempData["message"] = "Categoria a fost modificata";
                    return RedirectToAction("Index");
                }

                catch (Exception e)
                {
                    return View(cat);
                }
            
            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
           
            Category category = db.Categories.Find(id);
            if(category == null)
            {
                TempData["message"] = "Categoria nu exista";
                return RedirectToAction("Index");
            }
               
            return View(category);
            
          
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, Category requestCategory)
        {         
            Category category = db.Categories.Find(id);
            if (category != null)
            {
                if (ModelState.IsValid)
                {
                    category.CategoryName = requestCategory.CategoryName;
                    db.SaveChanges();
                    TempData["message"] = "Categoria a fost modificata";

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(requestCategory);
                }
            }
            else {
                TempData["message"] = "Categoria nu exista";
                return RedirectToAction("Index");
            }


        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {

            Category category = db.Categories.Find(id);
            if (category != null)
            {
                db.Categories.Remove(category);
                db.SaveChanges();
                TempData["message"] = "Categoria a fost stears";
            }
            else
            {
                TempData["message"] = "Categoria nu exista";
             
            }
            return RedirectToAction("Index");

        }
    }
}

ProiectV1/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProiectV1.Data;
using ProiectV1.Models;

namespace ProiectV1.Controllers
{
    //[Authorize]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<Profile> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private IWebHostEnvironment _env;


        public ProductsController(  ApplicationDbContext context,
                                    UserManager<Profile> userManager,
                                    RoleManager<IdentityRole> roleManager,
                                    IWebHostEnvironment env)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _env = env;
        }




        //[Authorize(Roles ="User,Colaborator,Admin")]
        public IActionResult Index()
        {   


            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            Privileges();

            var products = db.Products.Include("Category").Include("User")
                                      .Where(prod => prod.Approved == true);

            //                                         MOTOR DE CAUTARE

            var search = "";


            //cautare in continut sau titlu
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim(); // eliminam spatiile libere

                products = db.Products.Include("Category")
                                      .Include("User")
                                      .Where(prod => prod.Approved == true && ( prod.Title.Contains(search)
                                                                             || prod.Description.Contains(search) ) );
            }

            ViewBag.SearchString = search;

            //                                   Sortare Pret+ stele
            var sortPret = Convert.ToString(HttpContext.Request.Query["sortPret"]);
            var sortStele = Convert.ToString(HttpContext.Request.Query["sortStele"]);
            //verific daca cele 2 criteri sunt valide.
            if (sortPret != "asc" && sortPret != "desc")
                sortPret = "";
            if (sortPret != "asc" && sortPret != "desc")
                sortPret = "";
            
            //se sorteaza dupa criteriul sp*Price and ss*Starts
            var sp = 0;
            var ss = 0;
            if ( sortPret =="asc")
                sp = 1;
            if (sortPret == "desc")
                sp = -1;

            if (sortStele == "asc")
                ss = 1;
            if (sortStele == "desc")
                ss = -1;

            products = products.OrderBy(prod => sp*prod.Price).ThenBy(prod=> ss*prod.Stars);

            ViewBag.sortPret = sortPret;
            ViewBag.sortStele = sortStele;





            //                                         paginare

            var perPage = 6;

            //teremin numarul paginii
            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            //iau  perPage elemente
            int offset = currentPage* perPage;
            
            var pageProducts = products.Skip(offset).Take(perPage);

            //detrmin numarul de pagini;
            ViewBag.lastPage =  Math.Ceiling( (float)products.Count() / (float)perPage )-1;


            ViewBag.currentPage = currentPage;

            ViewBag.Products = pageProducts;



            if(search == ""  &&  sortStele =="" &&  sortPret=="")
            {
                ViewBag.PaginationBaseUrl = "/Products/Index/?page";
            } else
            {
                ViewBag.PaginationBaseUrl = "/Products/Index/?sortPret=" + sortPret + "&sortStele="+sortStele+"&search=" + search + "&page";
            }


            return View();
        }



        //[Authorize(Roles = "User,Colaborator,Admin")]
        public IActionResult Show(int id)
        {
            var p=db.Products.Find(id);

            if (p == null)
            {
                TempData["message"] = "Produsul nu exista";
                return RedirectToAction("Index");
            }
            else
            {
            Product product = db.Products   .Include("Category")
                                            .Include("User")
                                            .Include("Reviews")
                                            .Include("Reviews.User")
                               .Where(prod => prod.Id == id)
                               .First();

                product.Stars = System.Math.Round(StarAvr(product.Id), 2);
                p.Stars = product.Stars;
                db.SaveChanges();
                //detremin daca e colaboratorului sau e admin si id-ul user-ului.
                Privileges();
                return View(product);
            }
        }



        //add review
        [HttpPost]
        //[Authorize(Roles = "User,Editor,Admin")]
        public IActionResult Show([FromForm] Review review)
        {

            review.Date = DateTime.Now;
            review.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                db.Reviews.Add(review);
                db.SaveChanges();
                return Redirect("/Products/Show/" + review.ProductId);
            }
            else 
            {
                Product product = db.Products.Include("Category")
                                            .Include("User")
                                            .Include("Reviews")
                                            .Include("Reviews.User")
                               .Where(prod => prod.Id == review.ProductId)
                               .First();
                Privileges();
                return View(product);
            }
        }



        //calculeaz media stelelor
        private double StarAvr(int idProduct) {
            var reviews = db.Reviews.Where(rev => rev.ProductId == idProduct);
            if (reviews.Count()==0)
                return 0;
            double avr = 0;
            foreach(var rev in reviews)
                avr += rev.Stars;
            return avr / reviews.Count();
            
        }
        
        
        private void Privileges()
        {
            ViewBag.IsColaborator = User.IsInRole("Colaborator");
            ViewBag.IsAdmin = User.IsInRole("Admin");
            ViewBag.UserId = _userManager.GetUserId(User);
        }



        [Authorize(Roles ="Admin,Colaborator")]
        public IActionResult New()
        {
            Product product = new Product();
            product.Categ = GetAllCategories();
            return View(product);
        }



        // Se adauga articolul in baza de date
        [HttpPost]
        [Authorize(Roles = "Admin,Colaborator")]
        public async Task<IActionResult> New(Product product, IFormFile ProductPhoto)
        {
            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }
            //daca exista poza
            if (ProductPhoto!=null) {
                var id = DateTime.Now.ToString("yymmssfff") + ProductPhoto.FileName;
                product.Photo =GetDatabaseFileName(id); 
                SaveImgToMemory(ProductPhoto,id);
            }
            else//nu am poza =>ma redirectioneaza la pagina de new
            {
                TempData["message"] = "Imaginea este obligatorie";
                product.Categ = GetAllCategories();
                return View(product);
            }
            //salvez poza in baza de date
            product.Stars = 0;
            product.UserId = _userManager.GetUserId(User);
            product.Approved = false;

            if(ModelState.IsValid)
            {   
                db.Products.Add(product);
                db.SaveChanges();
                TempData["message"] = "Produsul a fost adaugat";
                return RedirectToAction("Index");


            }else 
            {
                product.Categ = GetAllCategories();
                return View(product);
            }
        }



        [Authorize(Roles = "Admin,Colaborator")]
        public IActionResult Edit(int id)
        {
            if (db.Products.Find(id) != null)
            {
                Product product = db.Products.Include("Category")
                                            .Where(art => art.Id == id)
                                            .First();

                product.Categ = GetAllCategories();
                if (product.UserId == _userManager.GetUserId(User) || User.IsInRole("Admin"))
                {
                    return View(product);
                }
                else
                {
                    TempData["message"] = "Nu ameti dreptul sa faceti modificari asupra produsului";
                    return RedirectToAction("Index");
                }
            }else
            {
                TempData["message"] = "Nu exista acest produs";
                return RedirectToAction("Index");
            }
    
        }

        
        [HttpPost]
        [Authorize(Roles = "Admin,Colaborator")]
        public async Task<IActionResult> Edit(int id, Product requestProduct, IFormFile ProductPhoto)
        {

            //salvez poza
            if (ProductPhoto != null)
            {
                var idPhoto = DateTime.Now.ToString("yymmssfff") + ProductPhoto.FileName;
                SaveImgToMemory(ProductPhoto, idPhoto);
                requestProduct.Photo = GetDatabaseFileName(idPhoto);
            }
          
            //fac editul

ProiectV1/Controllers/ProfilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProiectV1.Data;
using ProiectV1.Models;

namespace ProiectV1.Controllers
{
    public class ProfilesController : Controller
    {
        
        private readonly UserManager<Profile> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ProfilesController(  UserManager<Profile> userManager,
                                    RoleManager<IdentityRole> roleManager
                                    )
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {

            var profiles = _userManager.Users;
            var mydict = new Dictionary<Profile,IList<string>>();
            foreach (var profile in profiles)
            {
                mydict.Add(profile, _userManager.GetRolesAsync(profile).Result);
            }
           
            ViewBag.Profiles = mydict;
            ViewBag.test = profiles;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult EditRoll(string id) 
        {

            var profile = _userManager.FindByIdAsync(id).Result;

            if(profile ==null)
            {
                TempData["message"] = "Nu exista acest profil";
                return RedirectToAction("Index");
            }

            profile.AllRoles = GetAllRoles();
            profile.RoleId = _userManager.GetRolesAsync(profile).Result.First();

            return View(profile);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
      
        public async Task<IActionResult> EditRoll(string id,Profile requestProfile)
        {

          
           
            if(ModelState.IsValid)
            {
                var roles = await _userManager.GetRolesAsync(requestProfile);

                var newRole = _roleManager.FindByIdAsync(requestProfile.RoleId).Result;

                requestProfile = await _userManager.FindByIdAsync(id);

                await _userManager.RemoveFromRolesAsync(requestProfile, roles);
                await _userManager.AddToRoleAsync(requestProfile, newRole.Name);

                return RedirectToAction("Index");
                }
            else
            {
                requestProfile.AllRoles = GetAllRoles();
                return View(requestProfile);
            }
        }

        
        [NonAction]
        private List<SelectListItem> GetAllRoles()
        {
            var selectList = new List<SelectListItem>();

            var roles = _roleManager.Roles;

            foreach (var role in roles)
            {
                selectList.Add(new SelectListItem
                {
                    Value = role.Id.ToString(),
                    Text = role.Name.ToString()
                });
            }
            return selectList;
        }
    }
}

ProiectV1/Views/Shared/ProductInfo.cshtml
<div>

    <h3 class="card-title bg-color2 py-3 px-3 rounded-2 text-center">@Model.Title</h3>
    <div class="card-text text-center">@Model.Description</div>
    <div class="card-text text-center">@Model.Price $</div>
    <div><i class="bi bi-person"></i>@Model.User.UserName</div>

</div>

ProiectV1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProiectV1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProiectV1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProiectV1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @{// user-ul neinregistrat sau user-ul normal pot vedea doar categoriile si produsele
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Produse</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categorii</a>
                        </li>

                        @if(User.IsInRole("Admin")){

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="IndexAdmin">Produse Neaprobate</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="New">Adauga Produs</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="New">Adauga Categorie</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="Index">Utilizatori</a>
                            </li>
                        }

                        @if(User.IsInRole("Colaborator")){

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="New">Adauga Produs</a>
                            </li>

                        }

                        
                    </ul>
                    
                    <a class="nav-link text-dark mr-2" asp-area="" asp-controller="Carts" asp-action="Index"><i class="bi bi-cart"></i>Cart</a>
                    <partial name="_LoginPartial" />
                  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProiectV1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>